version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/pentafon-qa-analysis  # Cambia esto a la ubicación de tu proyecto en EC2

hooks:
  BeforeInstall:
    - location: scripts/setup_nginx.sh  # Script para crear configuraciones de Nginx
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu