export const CUSTOMER_VARS = [
  { value: '{customerId}', label: 'ID Cliente' },
  { value: '{accountNumber}', label: 'Número Cliente' },
  { value: '{name}', label: 'Nombre Cliente' },
  { value: '{fatherLastName}', label: 'Apellido Paterno' },
  { value: '{motherLastName}', label: 'Apellido Materno' },
  { value: '{phone}', label: 'Teléfono' },
  { value: '{phone2}', label: 'Teléfono 2' },
  { value: '{whatsapp}', label: 'Whatsapp' },
  { value: '{email}', label: 'Correo' },
  { value: '{balanceDue}', label: 'Saldo Vencido' },
  { value: '{promotion}', label: 'Promoción' },
  { value: '{daysPastDue}', label: 'Días Vencidos' },
  { value: '{paymentDueDate}', label: 'Fecha Vencimiento Pago' },
  { value: '{field1}', label: 'Campo 1' },
  { value: '{field2}', label: 'Campo 2' },
  { value: '{field3}', label: 'Campo 3' },
  { value: '{field4}', label: 'Campo 4' },
  { value: '{field5}', label: 'Campo 5' },
  { value: '{field6}', label: 'Campo 6' },
  { value: '{field7}', label: 'Campo 7' },
  { value: '{field8}', label: 'Campo 8' },
  { value: '{field9}', label: 'Campo 9' },
  { value: '{field10}', label: 'Campo 10' },
  { value: '{field11}', label: 'Campo 11' },
  { value: '{field12}', label: 'Campo 12' },
  { value: '{field13}', label: 'Campo 13' },
  { value: '{field14}', label: 'Campo 14' },
  { value: '{field15}', label: 'Campo 15' },
  { value: '{field16}', label: 'Campo 16' },
  { value: '{field17}', label: 'Campo 17' },
  { value: '{field18}', label: 'Campo 18' },
  { value: '{field19}', label: 'Campo 19' },
  { value: '{field20}', label: 'Campo 20' },
  { value: '{controlGroup}', label: 'Grupo control' },
];

export const SPECIAL_VARS = [{ value: '{todayFormatted}', label: 'Fecha actual' }];
