export const CHANNELS = Object.freeze({
  WHATSAPP: 1,
  SMS: 2,
  EMAIL: 3,
  VOICEBOT: 4,
});

export const CONTACT_FIELDS = Object.freeze([
  { name: 'Teléfono', value: 'phone' },
  { name: 'Teléfono 2', value: 'phone2' },
  { name: 'WhatsApp', value: 'whatsapp' },
]);

export const attemptsReportHeaders = [
  { key: 'customerId', displayLabel: 'attempts_reports_column_customer_id' },
  { key: 'accountNumber', displayLabel: 'attempts_reports_column_account_number' },
  { key: 'name', displayLabel: 'column_name' },
  { key: 'fatherLastName', displayLabel: 'column_last_father_name' },
  { key: 'motherLastName', displayLabel: 'column_last_mother_name' },
  { key: 'phone', displayLabel: 'column_phone' },
  { key: 'phone2', displayLabel: 'column_phone_2' },
  { key: 'whatsapp', displayLabel: 'Whatsapp' },
  { key: 'email', displayLabel: 'email' },
  { key: 'balanceDue', displayLabel: 'column_balance_due' },
  { key: 'promotion', displayLabel: 'column_promotion' },
  { key: 'daysPastDue', displayLabel: 'column_days_past_due' },
  { key: 'paymentDueDate', displayLabel: 'column_payment_due_date' },
  { key: 'field1', displayLabel: 'column_field_1' },
  { key: 'field2', displayLabel: 'column_field_2' },
  { key: 'field3', displayLabel: 'column_field_3' },
  { key: 'field4', displayLabel: 'column_field_4' },
  { key: 'field5', displayLabel: 'column_field_5' },
  { key: 'field6', displayLabel: 'column_field_6' },
  { key: 'field7', displayLabel: 'column_field_7' },
  { key: 'field8', displayLabel: 'column_field_8' },
  { key: 'field9', displayLabel: 'column_field_9' },
  { key: 'field10', displayLabel: 'column_field_10' },
  { key: 'field11', displayLabel: 'column_field_11' },
  { key: 'field12', displayLabel: 'column_field_12' },
  { key: 'field13', displayLabel: 'column_field_13' },
  { key: 'field14', displayLabel: 'column_field_14' },
  { key: 'field15', displayLabel: 'column_field_15' },
  { key: 'field16', displayLabel: 'column_field_16' },
  { key: 'field17', displayLabel: 'column_field_17' },
  { key: 'field18', displayLabel: 'column_field_18' },
  { key: 'field19', displayLabel: 'column_field_19' },
  { key: 'field20', displayLabel: 'column_field_20' },
  { key: 'controlGroup', displayLabel: 'column_control_group' },
  // { key: 'ladaTimeZone', displayLabel: 'Zona horaria' },
  // { key: 'paymentPromiseDate', displayLabel: 'Fecha promesa de pago' },
  { key: 'paymentCommitmentDate', displayLabel: 'column_payment_commitment_date' },
  { key: 'typification', displayLabel: 'column_typification' },
  { key: 'lastContactDate', displayLabel: 'column_last_attempt_created_at' },
  { key: 'actionChannel', displayLabel: 'channel' },
  { key: 'contactActionId', displayLabel: 'column_contact_action_id' },
  { key: 'id', displayLabel: 'column_interaction_id' },
  { key: 'contactDate', displayLabel: 'column_contact_date' },
  { key: 'contactTime', displayLabel: 'column_contact_time' },
  { key: 'callDuration', displayLabel: 'column_call_duration' },
  { key: 'actionStatus', displayLabel: 'status' },
];
